FROM openjdk:17

ARG JAR_FILE=build/libs/*.jar

COPY ConnectingChips-Back-Data/application.yml application.yml

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=prod", "/app.jar"]