FROM openjdk:17-jdk

# jar I HE
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +× ./gradlew
RUN ./gradlew bootjar

# JAR_FILE 변수 정의 -> 기본적으로 jar file이 2개이기 때문에 이름을 특정해야함
ARG JAR_FILE=build/libs/samchips-0.0.1-SNAPSHOT.jar

# JAR 파일 메인 디렉토리에 복사
COPY ${JAR_FILE} app.jar

# 시스템 진입점 정의 -> 컨테이너 실행 시 반드시 실행될 명령어
ENTRYPOINT ["java","-jar","/app.jar"]
